/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Encounter;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author shubhangisrivastava
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    PersonDirectory history;
    PatientDirectory history1;
    Encounter history2;
    //Encounter history3;
    
    public MainJFrame() {
        initComponents();
        
        history = new PersonDirectory();
        history1 = new PatientDirectory();
        history2 = new Encounter();
       // history3 = new Encounter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane3 = new javax.swing.JSplitPane();
        controlPanel3 = new javax.swing.JPanel();
        btnCreate3 = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnViewPatients = new javax.swing.JButton();
        btnEncounterList = new javax.swing.JButton();
        workPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane3.setBackground(new java.awt.Color(204, 204, 255));

        controlPanel3.setBackground(new java.awt.Color(0, 204, 204));

        btnCreate3.setText("Create Person");
        btnCreate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate3ActionPerformed(evt);
            }
        });

        btnView.setText("View Person ");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnViewPatients.setText("View Patients");
        btnViewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientsActionPerformed(evt);
            }
        });

        btnEncounterList.setText("View Encounter List");
        btnEncounterList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncounterListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanel3Layout = new javax.swing.GroupLayout(controlPanel3);
        controlPanel3.setLayout(controlPanel3Layout);
        controlPanel3Layout.setHorizontalGroup(
            controlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnView)
                        .addComponent(btnCreate3))
                    .addComponent(btnViewPatients, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEncounterList, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        controlPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreate3, btnEncounterList, btnView, btnViewPatients});

        controlPanel3Layout.setVerticalGroup(
            controlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanel3Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnCreate3)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addGap(18, 18, 18)
                .addComponent(btnViewPatients)
                .addGap(18, 18, 18)
                .addComponent(btnEncounterList)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        controlPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreate3, btnEncounterList, btnView, btnViewPatients});

        splitPane3.setLeftComponent(controlPanel3);

        workPanel.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/shubhangisrivastava/Downloads/imgbin-physician-patient-doctor-C3pgmf5mJctj9PbhJHyJSqyYD.jpeg")); // NOI18N

        javax.swing.GroupLayout workPanelLayout = new javax.swing.GroupLayout(workPanel);
        workPanel.setLayout(workPanelLayout);
        workPanelLayout.setHorizontalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        workPanelLayout.setVerticalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 601, Short.MAX_VALUE)
        );

        splitPane3.setRightComponent(workPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate3ActionPerformed

        CreatePersonJPanel createPanel = new CreatePersonJPanel(history);
        splitPane3.setRightComponent(createPanel);

    }//GEN-LAST:event_btnCreate3ActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

       ViewPersonJPanel viewPanel = new ViewPersonJPanel(history,history1,history2);
        splitPane3.setRightComponent(viewPanel);

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnViewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientsActionPerformed
        
       ViewPatientJPanel viewPatientPanel = new ViewPatientJPanel(history1,history2);
        splitPane3.setRightComponent(viewPatientPanel);
    }//GEN-LAST:event_btnViewPatientsActionPerformed

    private void btnEncounterListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncounterListActionPerformed
       ViewEncounterListJPanel viewEncounterList = new ViewEncounterListJPanel(history2);
        splitPane3.setRightComponent(viewEncounterList);
    }//GEN-LAST:event_btnEncounterListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate3;
    private javax.swing.JButton btnEncounterList;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewPatients;
    private javax.swing.JPanel controlPanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane3;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
