/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.EncounterHistory;
import model.PatientDetails;
import model.PatientDirectory;
import model.PersonDetails;
import model.PersonDirectory;
import model.VitalSigns;
import ui.ViewPersonJPanel;

/**
 *
 * @author shubhangisrivastava
 */
public class ViewPatientJPanel extends javax.swing.JPanel {

    
    
    PatientDirectory history1;
    Encounter history3;
    EncounterHistory enchistory;
    
    
    /**
     * Creates new form ViewPatientJPanel
     * @param history1
     */
    public ViewPatientJPanel(PatientDirectory history1,Encounter history3) {
        initComponents();
        this.history1=history1;
       this.history3=history3;
        this.enchistory=enchistory;
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTtile = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        btnAddNewEncounter = new java.awt.Button();
        lblPatientID = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        lblDateOfVisit = new javax.swing.JLabel();
        txtDateOfVisit = new javax.swing.JTextField();
        lblTemperature = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        lblBloodPressure = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        btnSave = new java.awt.Button();

        lblTtile.setFont(new java.awt.Font("Chalkboard", 1, 18)); // NOI18N
        lblTtile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTtile.setText("View Patient Details");

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient ID", "Date OF Visit", "Age", "Gender", "Address", "Community", "City", "Temperature", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPatient);
        if (tblPatient.getColumnModel().getColumnCount() > 0) {
            tblPatient.getColumnModel().getColumn(0).setHeaderValue("Patient Name");
            tblPatient.getColumnModel().getColumn(3).setHeaderValue("Age");
            tblPatient.getColumnModel().getColumn(4).setHeaderValue("Gender");
            tblPatient.getColumnModel().getColumn(5).setHeaderValue("Address");
            tblPatient.getColumnModel().getColumn(6).setHeaderValue("Community");
            tblPatient.getColumnModel().getColumn(7).setHeaderValue("City");
        }

        btnAddNewEncounter.setLabel("Visit Again");
        btnAddNewEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEncounterActionPerformed(evt);
            }
        });

        lblPatientID.setText("Patient ID :");

        txtPatientID.setEnabled(false);

        lblDateOfVisit.setText("Date Of Visit :");

        txtDateOfVisit.setEnabled(false);
        txtDateOfVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfVisitActionPerformed(evt);
            }
        });

        lblTemperature.setText("Temperature");

        txtTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatureActionPerformed(evt);
            }
        });

        lblBloodPressure.setText("Blood Pressure :");

        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });

        btnSave.setLabel("Add Encounter");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTtile, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addGap(53, 53, 53))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBloodPressure)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPatientID)
                                    .addComponent(lblDateOfVisit)
                                    .addComponent(lblTemperature))
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateOfVisit, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(txtPatientID)
                                    .addComponent(txtTemperature)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnAddNewEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBloodPressure, txtDateOfVisit, txtPatientID, txtTemperature});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTtile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAddNewEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientID)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfVisit)
                    .addComponent(txtDateOfVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemperature))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodPressure)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBloodPressure, txtDateOfVisit, txtPatientID, txtTemperature});

    }// </editor-fold>//GEN-END:initComponents

    private void txtDateOfVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfVisitActionPerformed

    private void txtTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperatureActionPerformed

    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void btnAddNewEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEncounterActionPerformed

         
        int selectedRowIndex = tblPatient.getSelectedRow();
       
       if(selectedRowIndex<0) {
           JOptionPane.showMessageDialog(this, "Please select a row to view");
           return;
       }
       
       DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
       PatientDetails pd = (PatientDetails) model.getValueAt(selectedRowIndex, 0);
      
       
       txtPatientID.setText(String.valueOf(pd.getUnique_id()));
       
    }//GEN-LAST:event_btnAddNewEncounterActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        
        int unique_id = Integer.parseInt(txtPatientID.getText());
        String DOV = txtDateOfVisit.getText();
        float temperature = Float.parseFloat(txtTemperature.getText());
        double blood_pressure = Double.parseDouble(txtBloodPressure.getText());
        
        VitalSigns visn = history3.addNewEncounter();
        
        
        visn.setUnique_id(unique_id);
        visn.setDate_of_visit(DOV);
        visn.setTemperature(temperature);
        visn.setBlood_pressure(blood_pressure);
        
        JOptionPane.showMessageDialog(this, "New Encounter Added.");
        
        txtPatientID.setText("");
        txtDateOfVisit.setText("");
        txtTemperature.setText("");
        txtBloodPressure.setText("");
  
    }//GEN-LAST:event_btnSaveActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAddNewEncounter;
    private java.awt.Button btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblDateOfVisit;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTtile;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtDateOfVisit;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
    
    DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
    model.setRowCount(0);
    
    for(PatientDetails cd : history1.getHistory()) {
        
        Object[] row = new Object[10];
          
        row[0] = cd;
        row[1] = cd.getUnique_id();
        row[2]= cd.getDate_of_visit();
        row[3] = cd.getAge();
        row[4] = cd.getGender();
        row[5] = cd.getAddr();
        row[6] = cd.getCommunity();
        row[7] = cd.getCity();
        row[8] = cd.getTemperature();
        row[9] = cd.getBlood_pressure();
        
        model.addRow(row);
    }
    }




}
